### ISSUE TITLE
Редактор модулей

### ISSUE THREAD

**Issue by edele** [edele/priz#10]
**Последовательность действий редактора**
- Создать модуль
  - директория в папке `modules`
  - main.xml
  - mainpic.png
  - возможность сохранения модуля без добавления заданий
  - вставка заглушки, если не выбрана картинка
  - проверка валидности названия (в задании не должно быть символов `\/:*?"<>|` )
- Предоставить возможность добавлять задания в этот модуль
  - директория в папке выбранного модуля
  - main.xml
  - mainpic.png
  - добавление заданий даже после сохранения модуля
  - вставка заглушки, если не выбрана картинка
  - проверка валидности названия (в задании не должно быть символов `\/:*?"<>|` )
- Экспорт модуля в файл и импорт его из интерфейса программы

**Файловая структура**

```
modules/
|   Модуль 1/
|   |   Первое задание модуля 1/
|   |   |   main.xml
|   |   |   mainpic.png
|   |   Второе задание модуля 1/
|   |   |   main.xml
|   |   |   mainpic.png
|   |   main.xml
|   |   mainpic.png
|   Модуль 2/
|   |   Первое задание модуля 2/
|   |   |   main.xml
|   |   |   mainpic.png
|   |   Второе задание модуля 2/
|   |   |   main.xml
|   |   |   mainpic.png
|   |   main.xml
|   |   mainpic.png

```

В папке модуля файл `main.xml` — сериализованный объект класса `Module`. В папке каждого задания в модулях в этом файле объект класса `Task`.

**Comment by Jerico174** [comment]
FormEditModule и FormEditTask — пресозданные текстбоксы для редактирования 

```
label.Hide();
textBox.Show();
```
