### ISSUE TITLE
Незаметная кнопка «регистрация» 

### ISSUE THREAD

**Issue by edele** [edele/priz#17]
Кнопку «регистрация» на стартовом экране не очень хорошо видно – белый цвет на светло бирюзовом. Надо сделать как-то контрастней.
![image](https://f.cloud.github.com/assets/2607770/2390227/ba55f564-a957-11e3-944c-49144aaa1d87.png)

**Comment by edele** [comment]
Нужно у Иры уточнить как тут поступить

**Comment by RinaRai** [comment]
А так?
![2014-03-12 12-11-12 psd 100 rgb8](https://f.cloud.github.com/assets/6926398/2394214/39757cc0-a9ad-11e3-938b-ae303743f529.png)

**Comment by AlexSMK** [comment]
þÔÏ ÄÅÌÁÔØ Ó ÆÏÒÍÏÊ ÒÅÇÉÓÔÒÁÃÉÉ? ëÒÕÇ ÔÁËÏÇÏ ÖÅ Ã×ÅÔÁ?

2014-03-12 10:12 GMT+04:00 RinaRai notifications@github.com:

**Comment by RinaRai** [comment]
Я вижу это так
![2014-03-12 12 14 13](https://f.cloud.github.com/assets/6926398/2394230/b3e03540-a9ad-11e3-8eb8-7c82a3560883.png)

**Comment by edele** [comment]
Это из-за того, что отвечаешь через почту. 
[Лебедевский декодер](http://www.artlebedev.ru/tools/decoder/) показал это:

> Что делать с формой регистрации? Круг такого же цвета
> @AlexSMK

**Comment by RinaRai** [comment]
Заменить всё, как вариант

**Comment by edele** [comment]
Использовать цвет RGB(40, 179, 151)
