### ISSUE TITLE
Лишние пункты в контекстном меню текстовых полей

### ISSUE THREAD

**Issue by edele** [edele/priz#19]
На всех текстовых полях контекстное меню выглядит следующим образом. На мой взгляд, все пункты, ниже «Выделить все» пользователям не нужны и только будут порождать ненужные вопросы.
![image](https://f.cloud.github.com/assets/2607770/2390246/fc62cf5e-a957-11e3-8897-89c908966857.png)

**Comment by Jerico174** [comment]
Никак это не чинится. Всё.
