### ISSUE TITLE
Верстка

### ISSUE THREAD

**Issue by RinaRai** [edele/priz#23]
![nbmnmbbnm](https://f.cloud.github.com/assets/6926398/2394182/6ff0c472-a9ac-11e3-9451-6307adddfa50.png)
Что-то жуткое здесь творится. Предложи время, когда сядем и поправим это.

**Comment by AlexSMK** [comment]
Идель не пофиксил выход. Поэтому здесь взрыв

**Comment by AlexSMK** [comment]
Завтра можно сесть. Сегодня никак.

**Comment by edele** [comment]
@RinaRai, тебе удобно сегодня в 10 в скайпе связаться?

**Comment by RinaRai** [comment]
Могу в 22:30 или в 23:00
