### ISSUE TITLE
Tab Index

### ISSUE THREAD

**Issue by Jerico174** [edele/priz#55]

**Comment by Jerico174** [comment]
solved a long time ago

**Comment by edele** [comment]
Can't verify on macos

**Comment by Jerico174** [comment]
Won't do anything, coz its friday. Deal with it 😎

**Comment by edele** [comment]
Gonna keep it open till monday then

**Comment by Jerico174** [comment]
Pretty sure nothing will change

**Comment by Jerico174** [comment]
thanks.

**Comment by Jerico174** [comment]
Actually, not sure if it's really solved...
