### ISSUE TITLE
Гиф в явлениях

### ISSUE THREAD

**Issue by edele** [edele/priz#66]
уже думаю о файловой системе:

```
content/
    Звуковые/
        text.rtf
        anim.gif
    Механические/
        text.rtf
        anim.gif
        anim2.gif
```

**Comment by edele** [comment]
Не думаю, что стоит пытаться оживить гифки в ртф. Лучше их хранить просто файлами и показывать где-то после текста.

**Comment by Jerico174** [comment]
Есть предложение при добавлении нового задания, gif файл сохранять в папке с заданием, там же, где лежит его main.xml. При загрузке окна с заданием проверять папку на gif файлы, если есть - выводить в доп. поле каком-нибудь

**Comment by edele** [comment]
@Jerico174 :+1:
